services:
  app:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mmctf-tom.rule=Host(`mmctf-tom.sucss.org`)"
      - "traefik.http.routers.mmctf-tom.tls=true"
      - "traefik.http.routers.mmctf-tom.middlewares=authentik@file"
      - "traefik.http.services.mmctf-tom.loadbalancer.server.port=8000"

    networks:
      - traefik

networks:
  traefik:
    external: true
